# Generated by Django 5.0.6 on 2024-07-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='video_link',
            field=models.URLField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
