# Generated by Django 5.0.6 on 2024-07-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cost_item_price_remove_item_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='video_link',
        ),
        migrations.AddField(
            model_name='item',
            name='video',
            field=models.FileField(default='', upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(default='', max_length=300),
        ),
    ]
